camera_frame    : "camera_link"
results_topic   : "results"
project_path    : find(ros_visual)
image_topic     : "/chroma_proc/image"
image_dif_topic : "/chroma_proc/image_dif"
depth_topic     : "/depth_proc/image"
csv_fields      : "Timestamp, Rect_id, Rect_x, Rect_y, Rect_W, Rect_H, Meter_X, Meter_Y, Meter_Z, Top, Height, Distance"
min_depth       : 0
max_depth       : 6000
playback_topics : false
create_directory: true
write_csv       : true
display         : true
