depth_out_image_topic: "/depth_proc/image"
hor_field            : 58
ver_field            : 45
depth_width          : 640
depth_height         : 480
min_depth            : 0
max_depth            : 6000
